apiVersion: v1
kind: Service
metadata:
  name: clients-contracts-db
  namespace: vaudoise
  labels:
    app: clients-contracts-db
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: clients-contracts-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clients-contracts-db
  namespace: vaudoise
  labels:
    app: clients-contracts-db
spec:
  serviceName: clients-contracts-db
  replicas: 1
  selector:
    matchLabels:
      app: clients-contracts-db
  template:
    metadata:
      labels:
        app: clients-contracts-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: clients-contracts-db-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: clients-contracts-db-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clients-contracts-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
